name: OpenLangAI
options:
  bundleIdPrefix: com.AHTechnologies
configs:
  Debug: debug
  Release: release
schemes:
  OpenLangAI:
    build:
      targets:
        OpenLangAI: [run, test]
targets:
  OpenLangAI:
    type: application
    platform: iOS
    deploymentTarget: "18.2"
    sources:
      - OpenLangAI
    settings:
      INFO_PLIST_PATH: OpenLangAI/Info.plist
  AudioPipelineKit:
    type: framework
    platform: iOS
    sources:
      - Packages/AudioPipelineKit/Sources
  OpenAIClientKit:
    type: framework
    platform: iOS
    sources:
      - Packages/OpenAIClientKit/Sources
  SecureStoreKit:
    type: framework
    platform: iOS
    sources:
      - Packages/SecureStoreKit/Sources
  PersistenceKit:
    type: framework
    platform: iOS
    sources:
      - Packages/PersistenceKit/Sources
